CREATE TABLE [dbo].[BASICMGR_GENERAL_CLASSIFIER]
(
	[ID] [nvarchar](50) NOT NULL PRIMARY KEY,
	[PARENT_ID] [nvarchar](50) NOT NULL DEFAULT ' ',
	[CLASSIFIER_TYPE] [nvarchar](50) NOT NULL ,
	[DESCRIPTION] [nvarchar](255) NOT NULL,
	[BRANCH_CODE] [decimal](18, 0) NOT NULL,
	[SHORT_NAME] [nvarchar](10) NOT NULL DEFAULT ' ',
	[ISDEAULT] [int] NOT NULL DEFAULT 0,
	[ENTITY_ID] [nvarchar](50) NOT NULL DEFAULT ' ',
	[EXT_CODE] [nvarchar](50) NOT NULL DEFAULT ' ',
	[DESCRIPTION2] [nvarchar](255) NULL DEFAULT ' '
)
GO

CREATE TABLE [dbo].[CLIENT]
(
	[CID] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [CNAME] NVARCHAR(50) NOT NULL, 
	[CSURNAME] NVARCHAR(50) NOT NULL, 
    [CDOCTYPE] NVARCHAR(50) NOT NULL DEFAULT 'N/A', 
    [CDOCNUM] NVARCHAR(50) NOT NULL, 
    [CGENDER] NVARCHAR(50) NOT NULL DEFAULT 'N/A', 
    [CADDRESS] NVARCHAR(50) NULL, 
    [CPHONE1] NVARCHAR(50) NULL, 
    [CPHONE2] NVARCHAR(50) NULL, 
    [CEMAIL] NVARCHAR(50) NULL
)
GO

CREATE TABLE [dbo].[WORKER]
(
	[WID] NVARCHAR(50) NOT NULL PRIMARY KEY,
	[WNAME] NVARCHAR(50) NOT NULL,
    [WSURNAME] NVARCHAR(50) NOT NULL,
    [WDOCTYPE] NVARCHAR(50) NOT NULL, 
    [WDOCNUM] NVARCHAR(50) NOT NULL,
    [WPHONE1] NVARCHAR(50) NULL,   
	[WPHONE2] NVARCHAR(50) NULL,   
	[WTYPE] NVARCHAR(50) NOT NULL DEFAULT 'N/A',
    [WGENDER] NVARCHAR(50) NOT NULL DEFAULT 'N/A', 
    [WADDRESS] NVARCHAR(50) NULL, 
    [WEMAIL] NVARCHAR(50) NULL,
)
GO

CREATE TABLE [dbo].[LOAN]
(
	[LID] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [CID] NVARCHAR(50) NOT NULL, 
	[WID] NVARCHAR(50) NOT NULL, 
    [LOAN_VALUE] DECIMAL(18, 2) NOT NULL DEFAULT 'N/A', 
    [LPARCEL] INT NOT NULL, 
    [LTAX] DECIMAL(18, 2) NOT NULL DEFAULT 'N/A', 
    [LPAYMENT_VALUE] DECIMAL(18, 2) NOT NULL, 
    [LPARCEL_VALUE] DECIMAL(18, 2) NOT NULL, 
    [LINCOME] DECIMAL(18, 2) NOT NULL, 
    [LDATE] DATETIME NOT NULL, 
    [LBALANCE] DECIMAL(18, 2) NOT NULL, 
    CONSTRAINT [FK_LOAN_ToCLIENT] FOREIGN KEY ([CID]) REFERENCES [CLIENT]([CID]), 
    CONSTRAINT [FK_LOAN_ToWORKER] FOREIGN KEY ([WID]) REFERENCES [WORKER]([WID])
)
GO

/*
begin region
07/07/2022
Created by Túlio Benedito
*/
-- INSERT GENDER
INSERT INTO BASICMGR_GENERAL_CLASSIFIER
     VALUES
           ('GNR001','','GENDER_CLASSIFIER','MASCULINO',1,'M',0,'','',''),
           ('GNR002','','GENDER_CLASSIFIER','FEMININO',1,'F',0,'','','')
GO

-- INSERT DOCUMENT TYPE
INSERT INTO BASICMGR_GENERAL_CLASSIFIER
     VALUES
           ('DTP001','','DOCTYPE_CLASSIFIER','BILHETE DE IDENTIDADE',1,'BI',0,'','',''),
           ('DTP002','','DOCTYPE_CLASSIFIER','NUMERO UNICO DE IDENTIFICACAO TRIBUTARIA',1,'NUIT',0,'','','')
GO

CREATE VIEW [dbo].[vwClients]
	AS 
SELECT        dbo.CLIENT.CID, dbo.CLIENT.CNAME, dbo.CLIENT.CSURNAME, DOCTYPE.DESCRIPTION AS CDOCTYPE, dbo.CLIENT.CDOCNUM, GENDER.DESCRIPTION AS CGENDER, dbo.CLIENT.CADDRESS, dbo.CLIENT.CPHONE1, 
                         dbo.CLIENT.CPHONE2, dbo.CLIENT.CEMAIL
FROM            dbo.CLIENT INNER JOIN
                         dbo.BASICMGR_GENERAL_CLASSIFIER AS DOCTYPE ON dbo.CLIENT.CDOCTYPE = DOCTYPE.ID INNER JOIN
                         dbo.BASICMGR_GENERAL_CLASSIFIER AS GENDER ON dbo.CLIENT.CDOCTYPE = GENDER.ID
GO
/*
end region
07/07/2022
Created by Túlio Benedito
*/

-- INSERT WORKER_TYPE
INSERT INTO BASICMGR_GENERAL_CLASSIFIER
     VALUES
           ('WTY001','','WORKER_TYPE','AVALISTA',1,'AVALISTA',0,'','',''),
           ('WTY002','','WORKER_TYPE','SECRETARIA',1,'SECRETARIA',0,'','','')
GO
-- CREATE WORKERS VIEW
CREATE VIEW [dbo].[vwWorkers]
	AS 
SELECT        dbo.WORKER.WID, dbo.WORKER.WNAME, dbo.WORKER.WSURNAME, DOCTYPE.DESCRIPTION AS WDOCTYPE, dbo.WORKER.WDOCNUM, GENDER.DESCRIPTION AS WGENDER, 
WTYPE.DESCRIPTION AS WTYPE, dbo.WORKER.WADDRESS, dbo.WORKER.WPHONE1, dbo.WORKER.WPHONE2, dbo.WORKER.WEMAIL
FROM            dbo.WORKER INNER JOIN
                         dbo.BASICMGR_GENERAL_CLASSIFIER AS DOCTYPE ON dbo.WORKER.WDOCTYPE = DOCTYPE.ID INNER JOIN
                         dbo.BASICMGR_GENERAL_CLASSIFIER AS GENDER ON dbo.WORKER.WGENDER = GENDER.ID INNER JOIN
                         dbo.BASICMGR_GENERAL_CLASSIFIER AS WTYPE ON dbo.WORKER.WTYPE = WTYPE.ID
GO
----- CORRIGIR VIEW CLIENTS, CAMPO GENERO
ALTER VIEW [dbo].[vwClients]
	AS 
SELECT        dbo.CLIENT.CID, dbo.CLIENT.CNAME, dbo.CLIENT.CSURNAME, DOCTYPE.DESCRIPTION AS CDOCTYPE, dbo.CLIENT.CDOCNUM, GENDER.DESCRIPTION AS CGENDER, dbo.CLIENT.CADDRESS, dbo.CLIENT.CPHONE1, 
                         dbo.CLIENT.CPHONE2, dbo.CLIENT.CEMAIL
FROM            dbo.CLIENT INNER JOIN
                         dbo.BASICMGR_GENERAL_CLASSIFIER AS DOCTYPE ON dbo.CLIENT.CDOCTYPE = DOCTYPE.ID INNER JOIN
                         dbo.BASICMGR_GENERAL_CLASSIFIER AS GENDER ON dbo.CLIENT.CGENDER = GENDER.ID
GO

-- INSERT WORKER_TYPE GESTOR
INSERT INTO BASICMGR_GENERAL_CLASSIFIER
     VALUES
           ('WTY003','','WORKER_TYPE','GESTOR',1,'GESTOR',0,'','','')
GO

CREATE TABLE [dbo].[PARCEL] (
    [LID]      NVARCHAR (50)   NOT NULL,
    [PDATE]    DATETIME        NULL,
    [PORDER]   INT   NOT NULL,
    [PVALUE]   DECIMAL (18, 2) NULL,
    [PSTATUS]  INT             NULL,
    [PPENALTY] DECIMAL (18, 2) NULL,
    PRIMARY KEY CLUSTERED ([LID] ASC, [PORDER] ASC)
);


 /*
begin region
21/07/2022
Created by Túlio Benedito
*/

CREATE VIEW [dbo].[vwLoans]
AS
SELECT        dbo.LOAN.LID, dbo.CLIENT.CNAME AS CID, dbo.WORKER.WNAME AS WID, dbo.LOAN.LOAN_VALUE, dbo.LOAN.LPARCEL_TYPE, dbo.LOAN.LPARCEL_NUM, dbo.LOAN.LTAX, dbo.LOAN.LPAYMENT_VALUE, 
                         dbo.LOAN.LPARCEL_VALUE, dbo.LOAN.LINCOME, dbo.LOAN.LDATE, dbo.LOAN.LBALANCE, dbo.LOAN.LEXPIRED_DATE, dbo.LOAN.LPAYMENT_DATE
FROM            dbo.CLIENT INNER JOIN
                         dbo.LOAN ON dbo.CLIENT.CID = dbo.LOAN.CID INNER JOIN
                         dbo.WORKER ON dbo.LOAN.WID = dbo.WORKER.WID
GO
/*
end region
21/07/2022
Created by Túlio Benedito
*/

/*
begin region
22/07/2022
Created by Túlio Benedito
*/
CREATE VIEW vwParcels
AS
SELECT        dbo.PARCEL.LID, dbo.PARCEL.PDATE, dbo.PARCEL.PORDER, dbo.PARCEL.PVALUE, dbo.PARCEL.PSTATUS, dbo.PARCEL.PPENALTY
FROM            dbo.LOAN INNER JOIN
                         dbo.PARCEL ON dbo.LOAN.LID = dbo.PARCEL.LID
GO
/*
begin region
22/07/2022
Created by Túlio Benedito
*/